import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tech Makers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es">
        <head>
            <title>Makers Tech - Tienda de Tecnología</title>
            <meta name="description" content="Tienda online de tecnología con recomendaciones personalizadas."/>
            <link rel="icon" href="/favicon.ico"/>
            <link rel="icon" href="/favicon.png"/>

        </head>
        <body>{children}</body>
        </html>
    );
}

